Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,24 +41,26 @@ jobs:
     - name: Build Pelican site
       run: |
         source env/bin/activate
-        pelican content -s publishconf.py  # Pas besoin de spécifier le répertoire de sortie
+        pelican content -s publishconf.py
 
     - name: Check root folder
       run: |
         echo "Checking contents of the root folder after Pelican build..."
         ls -al .
 
-    - name: Debugging - List files in root
-      run: |
-        echo "Listing all files and directories at the root before archiving:"
-        find . -type f
-
     - name: Pause before archiving
       run: sleep 5
 
     - name: Archive artifact
       run: |
-        tar --exclude='./myenv' --ignore-failed-read --exclude-vcs-ignores -czf artifact.tar.gz *.html *.css *.js
+        tar --exclude='./myenv' --ignore-failed-read --exclude-vcs-ignores -czf artifact.tar.gz .
+
+    - name: Check if artifact exists
+      run: |
+        if [ ! -f "artifact.tar.gz" ]; then
+          echo "Artifact not found!"
+          exit 1
+        fi
 
     - name: Upload artifact
       uses: actions/upload-artifact@v4
